mozilla/nimbus-shared

.circleci/config.yml
.gitignore
bin/pack-artifact.sh
package.json

This will make it easier to work with the generated data from this repo before we have official releases.

Store artifacts in CI jobs

---

.circleci/config.yml
.eslintrc.js
bin/build-schemas.ts
package.json
types/messaging.ts
yarn.lock

Add basic ESLint+TypeScript config

---

bin/build-schemas.ts
types/normandy.ts

Document the Normandy arguments schemas

---

types/messaging.ts

Added a general schema for all messages in messaging system (the CFR one is not complete)

Add Standard Message Recipe schema

---

.circleci/config.yml
.gitignore
Makefile
bin/generate-schema-code.ts
bin/generate-type-guards.ts
index.ts
package.json
src/typeGuards.ts
tsconfig.json

Generate a useful NPM package

---

types/messaging.ts
types/specialMessageAction.ts
types/triggerAction.ts

Add CFR schema validation from mozilla-central

---

Makefile
README.md
index.ts
package.json
types/index.ts

I'm posting this as a PR to make sure that the automatically built versions of the package include the type information. If it works well, I'll merge it myself.

Export types to TS

---

.circleci/config.yml
.gitignore
CHANGELOG.md
README.md
bin/pack-artifact.sh
package-lock.json
package.json

After this merges I'll rename the repo and the npm package.
Fixes #31

Rename to nimbus-shared

---

README.md

This PR is mostly to check that CI is happy with the new branch name.
Fixed #36.

Note that the default branch is named main

---

Makefile

I think this will fix some of the issues that CI and Kate were running into.

Only use standard Make features

---

package-lock.json
package.json

I don't think this is being used anywhere, right?

Remove extra unused  package

---

bin/translate-data.ts
data/experiment-recipe-samples/_type
data/experiment-recipe-samples/pull-factor.json
data/test-data.toml
package-lock.json
package.json

This is some progress towards #39, but I ran out of time. Since I'm going to be gone next week, I wanted to post this in case it was useful to anyone.
Todo:

Translate data to JSON and make it available in the packages

---

data/Audiences.ts

Qualify audiences by release channel

---

.eslintrc.js
Makefile
README.md
bin/build-schemas.ts
bin/generate-data-code.ts
bin/generate-schema-code.ts
bin/translate-data.ts
data/experiment-recipe-samples/__nimbusMeta.toml
data/experiment-recipe-samples/_type
data/test-data.toml
docs/pages/dev/data.md
docs/pages/dev/schemas.md
docs/pages/usage/js-and-ts.md
docs/pages/usage/python.md
index.ts
python/mozilla_nimbus_shared/__init__.py
python/mozilla_nimbus_shared/data.json
python/pyproject.toml.template
types/index.ts
types/test.ts

So somehow #43 only really caught half my data changes, and the rest were lost to a bad `git rebase`. I was able to resurrect them from the depths of the `reflog`, and here they are. This really should have been in v0.0.4, but alas.
This should fix #62

Combine data into a single file and expose in packages

---

data/ExperimentDesignPresets.ts

Based on conversations with @tdsmith we will hard code the AA preset to use 1% of release and add more dynamic bucket sizing later.

Add count to AA preset fixes #69

---

.eslintrc.js
.github/ISSUE_TEMPLATE/release-checklist.md
.prettierignore
.prettierrc.json
.therapist.yml
CODE_OF_CONDUCT.md
Makefile
data/Audiences.ts
data/ExperimentDesignPresets.ts
docs/components/anchoredHeadings.tsx
docs/pages/_app.tsx
docs/pages/content/schemas.tsx
docs/pages/dev/setup.md
docs/tsconfig.json
package-lock.json
package.json
src/utils.ts
test/test-experiment-recipe-firefox.ts
types/experiments.ts
types/targeting.ts

Set up prettier

---

.circleci/config.yml
.github/ISSUE_TEMPLATE/release-checklist.md
docs/pages/dev/deployments.md

I suspect this will work, but we can only really tell by merging it and trying to make a release.

Set up automatic publishing on tags

---

data/Audiences.ts
types/targeting.ts

See https://github.com/mozilla/experimenter/issues/3138

Remove release from audiences (fixes #98)

---

data/ExperimentDesignPresets.ts
types/experiments.ts

Bug 1656500 - Remove userId from randomization unit

---

types/messaging.ts

Copy over schema changes to nimbus shared
https://phabricator.services.mozilla.com/D87016#2715956

Add extraParams to SHOW_FIREFOX_ACCOUNTS special action schema

---

data/ExperimentDesignPresets.ts
data/experiment-recipe-samples/__nimbusMeta.toml
data/experiment-recipe-samples/pull-factor.json
docs/pages/dev/data.md
docs/pages/usage/python.md
test/test-experiment-recipe-firefox.ts
types/experiments.ts

I noticed a few things that need to be updated with some of the renaming described here https://docs.google.com/document/d/16ekd-cXkJF8_UTgkZ3ufzJFusYz9htd5EE2NpIFFJp4/edit#

Rename platform to application, adjustments for Experimenter API v6

---

test/test-experiment-recipe-firefox.ts
types/experiments.ts

Numbers should be integers

---

CHANGELOG.md

Somehow an unlinted changelog made its way into main

Changelog linting

---

package-lock.json
package.json
types/experiments.ts

This reverts commit 5f6825978ca9969d7fa3759b7dea97a01329b916.

Revert "Add constraints for l10n string IDs (#243)"
