bin/build-schemas.ts, test/normandy-arguments.ts
It is expected that this will cause CI to fail at first, since there are unfixed errors. Those should be fixed with the second commit.
Fixes #4
=> Make unhandled promise errors in build and tests fatal

README.md, package.json
```
❯ node --version
v12.16.2
❯ yarn
yarn install v1.22.4
[1/5] Validating package.json...
error rapid-experiments-shared@0.0.1: The engine "node" is incompatible with
this module. Expected version "14". Got "12.16.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about
this command.
```
=> Require Node 14 explicitly

.circleci/config.yml, .eslintignore, .gitignore, Makefile, README.md, bin/build-schemas.ts, bin/generate-type-guards.ts, package.json, src/typeGuards.ts, src/utils.ts, test/normandy-arguments.ts, tsconfig.json, types/normandy.ts
In working on this, I ended up needing to have dependencies between build jobs, so I switched to using Make for the task running.
This works from a shell in this project, but won't currently work on another project. That's because it loads the schemas via synchronous filesystem access with some pretty inflexible paths. I plan to do more thinking to figure out how to best do this in a more useful way.
Fixes #7
=> Automatically generate type guards

test/test-experiment-recipe-firefox.ts, types/experiments.ts
Adds an experiment definition compatible with the current Firefox implementation.
See https://github.com/mozilla/nimbus-shared/pull/19 for previously closed PR (due to branch renaming)
=> Experiment definition, fixes #23

data/Audiences.ts, types/index.ts, types/targeting.ts
Providing SQL expressions in audience definitions that let us test group memberships will facilitate automatically sizing experiments.
=> Find audience sizes with telemetry

data/features/__nimbusMeta.toml, data/features/picture_in_picture.toml, data/features/pinned_tabs.toml, types/experiments.ts, types/features.ts
Based on the spec draft in https://docs.google.com/document/d/1fdBcYvC7u7HpevM6BHqDmOXqVnpS-0woHAFzjTc-EiQ/edit#heading=h.tdev6kcteg3c.
cf #38 -- I've ignored the questions about mobile products so far; it's possible a separate `fenix_telemetry` key on the Feature interface will be the way we can cross that bridge once we get to it.
I just picked a place to shove this code; I don't have strong feelings about how this is organized if anyone feels it should live somewhere else.
I named the Feature interface FeatureInterface to avoid stepping on its definition as a string in the Experiment type; I'd welcome feedback on how to resolve that.
=> Add feature types and some examples

data/ExperimentDesignPresets.ts, tsconfig.json, types/experiments.ts
Includes:
* Empty branch type
* Max value of 1% of the population
* Preset of 2 equal empty branches
In terms of implementation, using typesscript for this doesn't work particularly well if we want to generate everything on the python side (although it could be used for validation).
Note that this design has been reviewed / approved by @tdsmith
=> Design preset for A/A Experiment

data/ExperimentDesignPresets.ts, data/experiment-recipe-samples/pull-factor.json, test/test-experiment-recipe-firefox.ts, types/experiments.ts
Adding proposed duration and enrollment to the AA preset based on feedback from @tdsmith: 
Enrollment: 7 days
Duration: 28 days
=> Add enrollment and duration to AA preset fixes #68

docs/global_style.scss, docs/pages/_app.tsx
This would be my recommendation to make this work for Chrome, mostly by removing the subgrids
=> Adjust grid css for docs to work on chrome

data/Audiences.ts, types/targeting.ts
We added 'release' as part of the targeting expression but for Experimenter to mark it on an experiment we need to put it in its own field, rather than trying to parse it out of the filter expression.
=> Add firefox channel to audiences fixes #60

data/ExperimentDesignPresets.ts, docs/pages/content/schemas.tsx, types/experiments.ts
So I changed the preset to extend the `ExperimentRecipe` instead of the `Experiment` and removed the design specific types since it added a layer of indirection to that whole jazz and we only have one right now so I don't think it added anything?  We can revisit it when we have more types?
=> Add filter_expression and targeting to AA preset fixes #73

types/messaging.ts
* Update schema (DOH messages)
* Rename to match m-c
* Export required trigger and action schemas so we can import them in mochitests
Related: https://phabricator.services.mozilla.com/D83789
=> Bug 1652811 - Use nimbus-shared/messaging schema for validation in m-c

python/mozilla_nimbus_shared/__init__.py, python/mozilla_nimbus_shared/test.py
I think this will make the library easier to use, since it exposes all errors
from the schema validator, and it gives specific errors that can be imported
from this library instead of from deeper subdependencies.
Fixes #33 and fixes #34.
=> Make the errors thrown by the Python library more accessible

.github/ISSUE_TEMPLATE/release-checklist.md
Adding a more specific push command for folks whose default remote is not `mozilla`
=> Update release docs with more specific push command

docs/adr/0001-one-console-app.md
This is a retroactive record of a decision already made for future reference.
@tdsmith @emtwo @mostlygeek does this accurately reflect your understanding of the decision?
=> Add ADR for why we're building visualizations, intake, publishing as one tool

data/experiment-recipe-samples/pull-factor.json, test/test-experiment-recipe-firefox.ts, types/experiments.ts
After starting to implementing this in Desktop, I realized this is going to be problematic for testing on unbranded builds etc.
Let's remove this until we've thought it through properly.
=> remove channels

data/experiment-recipe-samples/mobile-a-a.json
@rfk Since we were making some breaking changes anyway, I made a couple of adjustments to flatten the schema and remove some unused fields in https://github.com/mozilla/nimbus-shared/commit/3f9f88cf71caca2598013908b2de1c8e619cc128.
Previously we made the format compatible with Normandy but that is no longer a requirement.
Here's an example validated against the schema – also open to suggestions if you have them!
=> Added example of mobile A/A experiment

docs/adr/0002-use-json-schema-nimbus-shared.md
This ADR retroactively documents our decision to use JSON-Schema + nimbus shared to document schemas for future reference.
For reviewers - does this look like an accurate representation of what is currently true and does it make sense?
=> Use JSON Schema and nimbus shared ADR

data/experiment-recipe-samples/mobile-a-a.json, data/experiment-recipe-samples/pull-factor.json, test/test-experiment-recipe-firefox.ts, tsconfig.json, types/experiments.ts
Fixes #130. I thought maybe `schemaVersion` would be more specific about what it refers to.
See #135 for an ADR that discusses how this would be used.
=> Add schemaVersion property

data/experiment-recipe-samples/cfr-82-83.json, data/experiment-recipe-samples/mobile-a-a.json, data/experiment-recipe-samples/pull-factor.json, types/experiments.ts
Because
* Automated analysis requires the channel to be exposed in the experiment DTO
This commit
* Adds channel: string to the experiment type
=> fix #146 feat(project): add channel to experiment type

types/experiments.ts
Alternatives here are:
* Just keep using "probeSets"
* Use an array of bare slugs
I think using an array of objects is more flexible in case we want to add more annotations later but maybe YAGNI. The use case I'm envisioning is letting someone identify all the experiments that had a given outcome as a primary outcome.
=> Add outcomes to DTO

data/ExperimentDesignPresets.ts, data/experiment-recipe-samples/mobile-a-a.json, data/experiment-recipe-samples/pull-factor.json, types/experiments.ts
Because remote settings does not expect `feature_value` to be `null`, but rather always an object, we should remove it from the schema altogether.
=> Feature value should not be null

.github/ISSUE_TEMPLATE/schema-change.md
Because
* Schema changes involve many order dependent changes in multiple projects including multiple clients and experimenter
* Without a coherent process it can be difficult to track the many stages and their progress
* Without a coherent process it is possible to make inadvertently breaking changes that affect active experiments
This commit
* Introduces an issue template for tracking Nimbus schema changes across all affected projects that should improve visibility and reduce errors
=> Schema Change Process

test/test-experiment-recipe-firefox.ts, types/experiments.ts
Because:
* we want to implement support for an isRollout flag in experiments
This commit:
* adds an isRollout boolean to the NimbusExperiment type
* introduces example recipes for both mobile and desktop for testing
=> EXP-1865 add isRollout boolean property to Experiment type

CHANGELOG.md, docs/adr/0007-desktop-glean-telemetry.md
This describes the decision on how to instrument Nimbus Desktop with Glean
=> Create ADR about Desktop Glean instrumentation

types/experiments.ts
Because
* Jetstream needs to know the actual enrollment end date to determine the set of enrolled clients to analyze
* The actual enrollment end date may be different from the proposed enrollment end date
This commit
* Adds enrollmentEndDate to the experiment type
* This field will only be consumed by Jetstream
* This field has no impact on client behaviour
=> fix #200 feat: add enrollmentEndDate to experiment type

data/ExperimentDesignPresets.ts, data/experiment-recipe-samples/desktop-98.json, test/test-experiment-recipe-firefox.ts, types/experiments.ts
This field was deprecated for some time and now we're finally removing it.
=> Remove the feature.enabled field from the FeatureConfig definition

types/experiments.ts
This field was used by the messaging system, but hasn't been been used
for ~2 years.
=> Remove Experiment.filter_expression

types/experiments.ts
Because
* We want the localizations field to be nullable so the key can be present even if there's no localizations
This commit
* Makes the localizations field nullable
=> fix #239: make localizations nullable

types/experiments.ts
Because
* We want the locales field to be nullable
This commit
* Adds null to the locales field type
=> fix #250: locales can be null
